name: Upload to S3

on:
  push:
    branches:
      - main # Adjust to your main branch name
    paths: # Adjust these to limit the trigger to changes in specific folders or files
      - 's3_file/**'
      - '.github/workflows/upload-to-s3.yml'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ap-southeast-1

      - name: Upload files to S3
        run: |
          aws s3 sync s3_file s3://idn-media-assignment-test/
